# Generated by Django 3.2.3 on 2021-05-27 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_alter_customer_entrydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='EntryDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 17, 19, 15, 519164)),
        ),
    ]
